server:
  port: 4075
  shutdown: "graceful"

management:
  health:
    redis:
      enabled: ${opal.redis.enabled:false}
  endpoint:
    health:
      show-details: "always"

  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.opal.controllers,uk.gov.hmcts.opal.authentication.controller
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/opal/"
  application:
    name: Opal File Handler Service
  security:
    oauth2:
      client:
        registration:
          internal-azure-ad:
            client-id: ${AAD_CLIENT_ID:00000000-0000-0000-0000-000000000000}
            client-secret: ${AAD_CLIENT_SECRET:}
            scope: api://${AAD_CLIENT_ID:00000000-0000-0000-0000-000000000000}/opalinternaluser
            redirect-uri: ${opal.frontend.url}/sso/login-callback
            logout-redirect-uri: ${opal.frontend.url}/sso/logout-callback
            authorization-grant-type: authorization_code
            response-type: code
            response-mode: form_post
            prompt: login
            issuer-uri: https://sts.windows.net/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/
            claims: preferred_username
            provider: internal-azure-ad-provider
        provider:
          internal-azure-ad-provider:
            authorization-uri: ${opal.azure.active-directory-justice-auth-uri}/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/oauth2/v2.0/authorize
            token-uri: ${opal.azure.active-directory-justice-auth-uri}/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/oauth2/v2.0/token
            jwk-set-uri: ${opal.azure.active-directory-justice-auth-uri}/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/discovery/v2.0/keys
            logout-uri: ${opal.azure.active-directory-justice-auth-uri}/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/oauth2/v2.0/logout
            reset-password-uri: ${opal.azure.active-directory-justice-auth-uri}/${AAD_TENANT_ID:00000000-0000-0000-0000-000000000000}/oauth2/v2.0/authorize

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${OPAL_FILE_HANDLER_DB_HOST:localhost}:${OPAL_FILE_HANDLER_DB_PORT:5432}/${OPAL_FILE_HANDLER_DB_NAME:opal-file-handler-db}${OPAL_FILE_HANDLER_DB_OPTIONS:}
    username: ${OPAL_FILE_HANDLER_DB_USERNAME:opal-db-user}
    password: ${OPAL_FILE_HANDLER_DB_PASSWORD:opal-db-password}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: OpalHikariCP
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: false
        log_slow_query: 9
        dialect: org.hibernate.dialect.PostgreSQLDialect
        connection:
          # Following setting is 'generally' suggested to be false, or a lot of work otherwise
          provider_disables_autocommit: false
          # The following mode is advised against? Used only with a JTA Datasource.
          # handler_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
  data:
    redis:
      url: ${REDIS_CONNECTION_STRING:redis://redis:6379}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration/ddl, classpath:db/migration/data/allEnvs, classpath:db/migration/data/nle, classpath:db/migration/data/dev}
    baseline-on-migrate: true
    ignoreMigrationPatterns: "*:missing"

opal:
  frontend:
    url: ${OPAL_FRONTEND_URL:http://localhost:4200}
  azure:
    active-directory-justice-auth-uri: https://login.microsoftonline.com
  testing-support-endpoints:
    enabled: ${TESTING_SUPPORT_ENDPOINTS_ENABLED:true}
  common:
    domain: file-handler
    content-digest:
      request:
        enforce: ${OPAL_COMMON_CONTENT_DIGEST_REQUEST_ENFORCE:true}
        auto-generate: ${OPAL_COMMON_CONTENT_DIGEST_REQUEST_AUTO_GENERATE:true}
      response:
        enforce: ${OPAL_COMMON_CONTENT_DIGEST_RESPONSE_ENFORCE:false}
        algorithm: ${OPAL_COMMON_CONTENT_DIGEST_RESPONSE_ALGORITHM:SHA-512}
      supported-algorithms:
        sha-512: SHA-512
  file-handler-service:
    file-store:
      connection-string: ${AZURE_STORAGE_CONNECTION_STRING:UseDevelopmentStorage=true}
    file-types:
      caps-report:
        container-name: caps-report
        feature-flag: CAPS-Report-file-transfer-job
        file-name-regex: ^CapFa\.GB\.\d{8}\.\d{6}\.xml$
        source: CAPS_REPORT
        target: OPAL
        sftp-username: ${BAIS_SFTP_CAPS_REPORT_USERNAME:}
      bteckoh-report:
        container-name: ${BTECKOH_REPORT_AZURE_STORAGE_CONTAINER:bteckoh-report}
    sftp:
      bais:
        host: ${BAIS_SFTP_CONNECTION_HOST:localhost}
        port: ${BAIS_SFTP_CONNECTION_PORT:2222}
        private-key: ${BAIS_SFTP_PRIVATE_KEY:}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    opal: ${OPAL_LOG_LEVEL:INFO}
    org:
      hibernate:
        stat: INFO
        SQL: INFO
        SQL_SLOW: INFO
        type:
          descriptor:
            sql:
              BasicBinder: WARN
        orm:
          jdbc:
            bind: INFO
launchdarkly:
  sdk-key: ${LAUNCH_DARKLY_SDK_KEY:}
  offline-mode: ${LAUNCH_DARKLY_OFFLINE_MODE:false}
  env: ${LAUNCH_DARKLY_ENV:default}
  enabled: ${LAUNCH_DARKLY_ENABLED:true}
  file:
    - ${LAUNCH_DARKLY_FILE:bin/utils/launchdarkly-flags.json}
  default-flag-values:
    release-1a: ${RELEASE_1A_ENABLED:false}
    release-1b: ${RELEASE_1B_ENABLED:false}
    release-1c: ${RELEASE_1C_ENABLED:false}
    release-1c-banking-interfaces: ${RELEASE_1C_BANKING_INTERFACES_ENABLED:false}

user:
  service:
    url: ${OPAL_USER_SERVICE_API_URL:http://localhost:4555}
azure:
  application-insights:
    instrumentation-key: ${opal.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
dbMigration:
  # When true, the app will run DB migration on startup.
  # Otherwise, it will just check if all migrations have been applied (and fail to start if not).
  runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}