#!/bin/sh
set -eu

sed -i '/^ChrootDirectory %h$/d' /etc/ssh/sshd_config

chown 1001:users /home/CAPS-report
chown 1002:users /home/BTEckoh-report
chown 1003:users /home/AllPay
chown 1004:users /home/DWP
chown 1005:users /home/NATWEST
chown 1006:users /home/Jacobs
chown 1007:users /home/BARCLAYCARD
chown 1008:users /home/CDER
chown 1009:users /home/BTEckoh
