opal:
  testing-support-endpoints:
    enabled: false
  file-handler-service:
    file-types:
      bteckoh-report:
        sftp-username: BTEckoh-report
      caps-report:
        sftp-username: CAPS-report
      bteckoh-transfer:
        sftp-username: BTEckoh
      natwest:
        sftp-username: NATWEST
      barclaycard:
        sftp-username: BARCLAYCARD
      bailiffs:
        jacobs:
          sftp-username: Jacobs
        cder:
          sftp-username: CDER

user:
  service:
    url: http://localhost:${INTEGRATION_WIREMOCK_PORT:4553}